### ISSUE TITLE
Faltan pruebas y se deberían mejorar otras

### ISSUE THREAD

**Issue by evolentini** [gzocco/TP3-IOT#1]
Faltan algunas pruebas, por ejemplo no se busca un dato que no esta en la lista. Ademas se buscan en todos los casos todas las claves almacenadas y esto no es necesario. Finalmente algunas pruebas quedarían más claras hubiera menos elementos y menos comparaciones que se repiten entre prueba y prueba. No hace falta probar n veces la misma cosa.

**Comment by gzocco** [comment]
Se agregan pruebas y se reducen algunos tests que son repetitivos.
